run:
  modules-download-mode: readonly

linters:
  presets:
    - bugs
    - unused
    - import
    - module

  enable:
    - gofumpt
    - lll
    - predeclared
    - gocognit
    - nestif

  disable:
    - scopelint

linters-settings:
  lll:
    line-length: 88
  gocognit:
    min-complexity: 10
  nestif:
    min-complexity: 3
