repos:
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-beta.4
  hooks:
  - id: go-mod-tidy
  - id: golangci-lint-repo-mod
    name: GolangCI Lint
  - id: go-test-repo-mod
    name: Test
