name: ci
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: project setup
        run: |
        make setup
        scripts/check_go_mod.sh

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1

      - name: js-lint
        run: make js-lint

      - name: test
        run: make test
